services:
  pohadkomat:
    image: pohadkomat:latest
    ports:
      - "9734:9734"
    volumes:
      - /data/share/Media/Pohadky:/media
      - ./cache:/cache
    environment:
      - "POHADKOMAT_BASE_URL=http://192.168.5.6:9734"
      - "POHADKOMAT_DEVICE_NAME=Bedroom speaker"
    privileged: true
    network_mode: host
