[[feeds]]
title = "Nedělní pohádky pro radost"
url = "https://anchor.fm/s/3d01f0f8/podcast/rss"

[[feeds]]
title = "Pohádky zdarma"
url = "http://justcast.herokuapp.com/shows/radek-spidla-pohadky-zdarma/audioposts.rss"                                                                                           
[[feeds]]
title = "Kolíbka - tajemné pohádky a příběhy"                                     
url = "https://zazrak.libsyn.com/rss"                                              

[[feeds]]
title = "Pohadkovidani"
url = "https://anchor.fm/s/674248f4/podcast/rss"

