[tool.poetry]
name = "pohadkomat"
version = "0.1.0"
description = ""
authors = ["Martastain <martas@imm.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pychromecast = "^14.0.5"
rich = "^13.9.4"
pydantic = "^2.10.5"
typer = "^0.15.1"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
